### ISSUE TITLE
crash in drawing 3d on 10.15.5and Xcode 11

### ISSUE THREAD

**Issue by pixelmad** [metal-by-example/sample-code#11]
-[MTLTextureDescriptorInternal validateWithDevice:]:1414: failed assertion `MTLTextureDescriptor: Depth, Stencil, DepthStencil, and Multisample textures must be allocated with the MTLStorageModePrivate or MTLStorageModeMemoryless storage mode.'

assert failed at     [self makeDepthTexture];
direct download of master branch in Xcode on macOS 

don't know how to fix or I wouldn't be reading your wonderful book-
metal is a mystery to me!!

**Comment by warrenm** [comment]
This should be fixed with 12d68a5.

Specifically, we now provide an explicit storage mode for the depth buffer [here](https://github.com/metal-by-example/sample-code/blob/12d68a510ce9d133ec0b1ec27caae674f73985d4/objc/04-DrawingIn3D/DrawingIn3D/MBEMetalView.m#L129). The same fix is applicable elsewhere.

**Comment by pixelmad** [comment]
thanks -
is there something simple i need to do?

**Comment by warrenm** [comment]
Nope--closing as fixed. Thanks for the report!
