### ISSUE TITLE
Crash in Drawing in 3D project on iOS Simulator (different from Issue #11)

### ISSUE THREAD

**Issue by matthewreagan** [metal-by-example/sample-code#12]
Running the Drawing in 3D sample project on 10.15.5 in the iPhone 8 simulator results in the assert below:

```validateFunctionArguments:3481: failed assertion `Vertex Function(vertex_project): the offset into the buffer uniforms that is bound at buffer index 1 must be a multiple of 256 but was set to 64.'```

The assert can be fixed by padding the `MBEUniforms` struct so it occupies 256 bytes, after which the project runs correctly. I don't know enough about the internals to know what the right way of fixing this is, however (would love to hear any insights since it would help further educate me).

Just to doubly-clarify: the project runs great on device, this only appears to occur in the simulator. Thanks for creating such a fantastic resource for Metal, Warren!

**Comment by warrenm** [comment]
Padding and alignment qualifiers work, but in my opinion, they're a blunt instrument. Metal's offset alignment requirement only requires that the offset be aligned, not the objects in the buffer. So if you pad, say, an instance uniform struct up from 64 bytes to 256 bytes, then _every instance_ contains 192 bytes of unused space.

My preference is instead to ensure that data is written to buffers starting at aligned offsets, so that when offsets are used during rendering, they're naturally aligned as required.

I've added the following declarations to most of the samples in the repository, and used them to calculate offsets in such a way that the samples should now run on the Mac and on the iOS Simulator:

```
static const uint32_t MBEBufferAlignment = 256;

static inline uint64_t AlignUp(uint64_t n, uint32_t alignment) {
    return ((n + alignment - 1) / alignment) * alignment;
}
```

Fixed in a73cc91. Thanks!
